#!/usr/bin/env node
// Builds data/meta/answer-index.json: saved answer key -> lesson and question text.
// Used only for plain-language backup and restore labels (UX-004).
// Rerun after changing lesson question or checklist IDs or wording:
//   node scripts/build_answer_index.js
'use strict';

var fs = require('fs');
var path = require('path');

var ROOT = path.join(__dirname, '..');
var MAX_TEXT = 90;

function plainText(html) {
    var text = String(html || '')
        .replace(/<[^>]*>/g, ' ')
        .replace(/&nbsp;/g, ' ')
        .replace(/&amp;/g, '&')
        .replace(/&quot;/g, '"')
        .replace(/&#39;|&rsquo;|&lsquo;/g, '\'')
        .replace(/\s+/g, ' ')
        .trim();
    return text.length > MAX_TEXT ? text.slice(0, MAX_TEXT - 3).replace(/\s+\S*$/, '') + '...' : text;
}

function buildIndex(dataDir) {
    var keys = {};
    fs.readdirSync(dataDir)
        .filter(function (name) { return /^\d{3}-\d{2}\.json$/.test(name); })
        .sort()
        .forEach(function (name) {
            var series = name.slice(0, 3);
            var lesson = parseInt(name.slice(4, 6), 10);
            var data = JSON.parse(fs.readFileSync(path.join(dataDir, name), 'utf8'));
            (data.blocks || []).forEach(function (block) {
                if (block.type === 'question' && block.id) {
                    keys['question-' + series + '-' + block.id] = { lesson: lesson, text: plainText(block.text) };
                } else if (block.type === 'checklist' && block.id) {
                    keys['checklist-' + series + '-' + block.id] = { lesson: lesson, text: plainText(block.prompt) };
                }
            });
        });
    return { note: 'Generated by scripts/build_answer_index.js. Labels only; do not edit by hand.', keys: keys };
}

function serialize(index) {
    return JSON.stringify(index, null, 1) + '\n';
}

if (require.main === module) {
    var out = path.join(ROOT, 'data', 'meta', 'answer-index.json');
    var index = buildIndex(path.join(ROOT, 'data'));
    fs.writeFileSync(out, serialize(index));
    console.log('Wrote ' + out + ': ' + Object.keys(index.keys).length + ' keys.');
}

module.exports = { buildIndex: buildIndex, serialize: serialize, plainText: plainText };
